### ISSUE TITLE
Nginx: Permission denied error

### ISSUE THREAD

**Issue by slima** [hardware/rainloop#10]
docker-compose:

```yml
  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    restart: unless-stopped
    volumes:
      - /mnt/docker/rainloop:/rainloop/data
    depends_on:
      - mailserver
      - mariadb
```

docker logs -f rainloop :

```
nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)
2017/08/28 10:40:52 [emerg] 349#349: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)
```
