### ISSUE TITLE
Add Kubernetes Objects

### ISSUE THREAD

**Issue by pojntfx** [hardware/rainloop#20]
It would be nice if there would be ready-to-use Kubernetes objects or even a Helm chart for this Docker container. I've already created a simple one for my personal use, but it would be great to see "upstream support".
Probably my [Rainloop Kubernetes Objects](https://gitlab.com/snippets/1744999) could be a starting point.

**Comment by hardware** [comment]
I'm not familiar with Kubernetes but if you want to make a pull request and help to write [some documentation](https://github.com/hardware/mailserver/issues/231), go for it :)

**Comment by pojntfx** [comment]
I'll look into it. I'll however not be able to provide docs for the whole mailserver - but for Rainloop, that should definitely be possible. I'm currently working on it over here (in the `mail` package, it's a monorepo):
[LibreSat GitLab Repo](https://gitlab.com/libresat/libresat)

**Comment by pojntfx** [comment]
I guess that creating a [Helm chart](https://helm.sh/) for Rainloop would be a good idea as well. Installing it would be as simple as `helm install rainloop`.

**Comment by dhemeier** [comment]
FYI, a helm chart based on this image was already created by @t13a:
https://github.com/t13a/helm-chart-rainloop

Also I run this Image inside my production cluster, currently with a manual deployment. This is my current deployment spec:

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rainloop-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rainloop-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: rainloop
      labels:
        app: rainloop
    spec:
      containers:
        - image: hardware/rainloop
          imagePullPolicy: Always
          name: rainloop
          resources:
            requests:
              memory: "56Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
          - containerPort: 8888
            name: web
          volumeMounts:
          - name: data
            mountPath: /rainloop/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: rainloop-pvc
```
